#!/usr/bin/env python3
"""Turn the standalone Noel page into something you can paste into WordPress.

Elementor can hold raw HTML, but not a whole HTML document — there is no <head>
to put a stylesheet link or meta tags in, and the assets live on GitHub Pages.
So this generates the snippet from index.html rather than keeping a second copy
by hand, because that second copy would be out of date within a day.

    python3 build-wordpress.py

Writes noel-wordpress.html: paste the whole file into one Elementor HTML widget
on a page whose layout is set to Elementor Canvas.
"""
import pathlib
import re

HERE = pathlib.Path(__file__).parent
SRC = HERE / "index.html"
OUT = HERE / "noel-wordpress.html"

# Where the images and audio actually live. Keeping them on Pages means the
# WordPress page works the moment it's pasted, with nothing to upload first.
ASSETS = "https://achyboy.github.io/noel-play/"

html = SRC.read_text(encoding="utf-8")

version = re.search(r'name="x-noel-version" content="([^"]+)"', html).group(1)
fonts = re.search(r'<link href="(https://fonts\.googleapis\.com[^"]+)"', html).group(1)
style = re.search(r"<style>(.*?)</style>", html, re.S).group(1)
body = html[html.index("<body>") + len("<body>"):html.index("</body>")]

# 1. A <link> in a widget is unreliable, and @import must be the first rule in
#    the sheet, so it goes at the very top.
prelude = f"@import url('{fonts}');\n"

# 2. Elementor Canvas is close to a blank page but still wraps the widget in its
#    own containers, which carry padding and a max-width.
prelude += """
/* Elementor wrappers: this page manages its own full-bleed layout. */
.elementor, .elementor-section, .elementor-container, .elementor-column,
.elementor-widget-wrap, .elementor-widget-html, .e-con, .e-con-inner, .e-child{
  max-width:none !important; padding:0 !important; margin:0 !important; width:100% !important}
/* The WordPress admin bar is fixed too, and would sit on top of our header —
   only ever seen by a logged-in editor, but it looks broken to whoever is
   building the page. */
body.admin-bar .bar{top:32px}
@media screen and (max-width:782px){ body.admin-bar .bar{top:46px} }
"""

# 3. Relative asset paths only resolve next to index.html on Pages.
for rel in re.findall(r"""['"(](hero\d+\.jpg|noel\.m4a|noel\.mp3|noel\.ics)['")]""", style + body):
    body = body.replace(f'"{rel}"', f'"{ASSETS}{rel}"').replace(f"'{rel}'", f"'{ASSETS}{rel}'")
    style = style.replace(f"'{rel}'", f"'{ASSETS}{rel}'").replace(f'"{rel}"', f'"{ASSETS}{rel}"')

banner = (
    "<!-- Noel — generated by build-wordpress.py, do not hand-edit.\n"
    f"     Source: index.html ({version}). Paste into ONE Elementor HTML widget\n"
    "     on a page set to the Elementor Canvas layout. -->\n"
)
# The meta tag is what the footer and the stale-cache check both read. It is not
# in <head> here, but querySelector finds it either way and the self-check regex
# still matches it in the fetched page.
meta = f'<meta name="x-noel-version" content="{version}">\n'

OUT.write_text(banner + meta + "<style>\n" + prelude + style + "</style>\n" + body, encoding="utf-8")

written = OUT.read_text()
leftovers = re.findall(r"""['"(](hero\d+\.jpg|noel\.m4a|noel\.ics)['")]""", written)
print(f"wrote {OUT.name}  ({OUT.stat().st_size:,} bytes)  from {version}")
print(f"  unresolved relative assets: {sorted(set(leftovers)) or 'none'}")

# Only a tag that OPENS A LINE is a real document tag. The script's own comments
# mention <head> in prose, and matching those was a false alarm.
for tag in ("<!DOCTYPE", "<html", "<head>", "</head>", "<body", "</body>"):
    bad = [i + 1 for i, line in enumerate(written.splitlines())
           if line.lstrip().startswith(tag)]
    assert not bad, f"document tag {tag} leaked at line(s) {bad}"
print("  no document tags leaked")
